#!/usr/bin/env python3
"""Build a deployable static ASMR & SAMR website package.

The source site intentionally loads ``config.local.js`` at runtime. This script
never copies the developer-local file. Instead, it writes a browser-visible
deployment config from environment variables, using safe placeholders when real
launch values are not available yet.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "website"
DEFAULT_OUTPUT = ROOT / "dist"

EXCLUDED_NAMES = {
    "__pycache__",
    ".pytest_cache",
    "config.local.js",
}

EXCLUDED_SUFFIXES = {
    ".pyc",
    ".pyo",
}


PUBLIC_CONFIG_FIELDS = {
    "supabaseUrl": ("ASMR_SAMR_SUPABASE_URL", "https://thpuomqhqghqskyegpfj.supabase.co"),
    "supabaseAnonKey": ("ASMR_SAMR_SUPABASE_ANON_KEY", "YOUR_SUPABASE_PUBLISHABLE_OR_ANON_KEY"),
    "whatsappNumber": ("ASMR_SAMR_WHATSAPP_NUMBER", "966560505651"),
    "siteDomain": ("ASMR_SAMR_SITE_DOMAIN", "https://asmr-samr.pages.dev"),
    "founderName": ("ASMR_SAMR_FOUNDER_NAME", "ASMR & SAMR Fragrances"),
    "instagramUrl": ("ASMR_SAMR_INSTAGRAM_URL", "https://instagram.com/asmr.samr.perfumes"),
    "productionCityEn": ("ASMR_SAMR_PRODUCTION_CITY_EN", "Riyadh"),
    "productionCityAr": ("ASMR_SAMR_PRODUCTION_CITY_AR", "الرياض"),
}


def should_copy(path: Path) -> bool:
    return path.name not in EXCLUDED_NAMES and path.suffix not in EXCLUDED_SUFFIXES


def copy_source(output: Path) -> None:
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)

    for item in SOURCE.rglob("*"):
        relative = item.relative_to(SOURCE)
        if any(part in EXCLUDED_NAMES for part in relative.parts):
            continue
        if not should_copy(item):
            continue
        destination = output / relative
        if item.is_dir():
            destination.mkdir(parents=True, exist_ok=True)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, destination)


def deployment_config() -> dict[str, object]:
    config: dict[str, object] = {}
    for key, (env_name, fallback) in PUBLIC_CONFIG_FIELDS.items():
        config[key] = os.environ.get(env_name, fallback).strip()

    reserved = os.environ.get("ASMR_SAMR_RESERVED_COUNT", "42").strip()
    try:
        config["reservedCount"] = max(0, int(reserved))
    except ValueError:
        config["reservedCount"] = 42

    config["adminRoles"] = ["admin", "manager", "finance", "marketing", "inventory", "production", "support"]
    config["adminRequireAuth"] = True
    return config


def write_runtime_config(output: Path) -> None:
    config = deployment_config()
    rendered = json.dumps(config, ensure_ascii=False, indent=2)
    (output / "config.local.js").write_text(
        "// Generated by scripts/build_static_site.py. Browser-visible public values only.\n"
        f"window.ASMR_SAMR_CONFIG = {rendered};\n",
        encoding="utf-8",
    )


def validate_output(output: Path) -> None:
    required = [
        output / "index.html",
        output / "app.js",
        output / "admin-dashboard.js",
        output / "style.css",
        output / "config.local.js",
        output / "assets",
    ]
    missing = [str(path.relative_to(output)) for path in required if not path.exists()]
    if missing:
        raise SystemExit(f"Deployment package missing required files: {', '.join(missing)}")

    local_source = (SOURCE / "config.local.js").read_text(encoding="utf-8") if (SOURCE / "config.local.js").exists() else ""
    built_config = (output / "config.local.js").read_text(encoding="utf-8")
    if local_source and built_config == local_source:
        raise SystemExit("Deployment config matches developer-local config; refusing to package.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the ASMR & SAMR static deployment package.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Output directory. Defaults to ./dist.")
    args = parser.parse_args()

    output = Path(args.output).resolve()
    copy_source(output)
    write_runtime_config(output)
    validate_output(output)
    print(f"Built static website package: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
